const CATALOGO_ETNIAS = [
    { id: "1", nombre: "Achuar" },
    { id: "2", nombre: "Aimara" },
    { id: "3", nombre: "Amahuaca" },
    { id: "4", nombre: "Arabela" },
    { id: "5", nombre: "Ashaninka" },
    { id: "6", nombre: "Asheninka" },
    { id: "7", nombre: "Awajún" },
    { id: "8", nombre: "Bora" },
    { id: "9", nombre: "Cashinahua" },
    { id: "10", nombre: "Chamicuro" },
    { id: "11", nombre: "Chapra" },
    { id: "12", nombre: "Chitonahua" },
    { id: "13", nombre: "Ese Eja" },
    { id: "14", nombre: "Harakbut" },
    { id: "15", nombre: "Ikitu" },
    { id: "16", nombre: "Iñapari" },
    { id: "17", nombre: "Iskonawa" },
    { id: "18", nombre: "Jaqaru" },
    { id: "19", nombre: "Jíbaro" },
    { id: "20", nombre: "Kakataibo" },
    { id: "21", nombre: "Kakinte" },
    { id: "22", nombre: "Kandozi" },
    { id: "23", nombre: "Kapanawa" },
    { id: "24", nombre: "Kichwa" },
    { id: "25", nombre: "Kukama Kukamiria" },
    { id: "26", nombre: "Madija" },
    { id: "27", nombre: "Maijuna" },
    { id: "28", nombre: "Marinahua" },
    { id: "29", nombre: "Mashco Piro" },
    { id: "30", nombre: "Mastanahua" },
    { id: "31", nombre: "Matsés" },
    { id: "32", nombre: "Matsigenka" },
    { id: "33", nombre: "Muniche" },
    { id: "34", nombre: "Murui-Muinani" },
    { id: "35", nombre: "Nahua" },
    { id: "36", nombre: "Nanti" },
    { id: "37", nombre: "Nomatsigenga" },
    { id: "38", nombre: "Ocaina" },
    { id: "39", nombre: "Omagua" },
    { id: "40", nombre: "Quechuas" },
    { id: "41", nombre: "Resigaro" },
    { id: "42", nombre: "Secoya" },
    { id: "43", nombre: "Sharanahua" },
    { id: "44", nombre: "Shawi" },
    { id: "45", nombre: "Shipibo-Konibo" },
    { id: "46", nombre: "Shiwilu" },
    { id: "47", nombre: "Ticuna" },
    { id: "48", nombre: "Urarina" },
    { id: "49", nombre: "Uro" },
    { id: "50", nombre: "Vacacocha" },
    { id: "51", nombre: "Wampis" },
    { id: "52", nombre: "Yagua" },
    { id: "53", nombre: "Yaminahua" },
    { id: "54", nombre: "Yanesha" },
    { id: "55", nombre: "Yine" },
    { id: "OTRO", nombre: "Otro (Especificar)" }
];

const CATALOGO_LENGUAS = [
    { id: "1", nombre: "Achuar" },
    { id: "2", nombre: "Aimara" },
    { id: "3", nombre: "Amahuaca" },
    { id: "4", nombre: "Arabela" },
    { id: "5", nombre: "Ashaninka" },
    { id: "6", nombre: "Asheninka" },
    { id: "7", nombre: "Awajún" },
    { id: "8", nombre: "Bora" },
    { id: "9", nombre: "Cashinahua" },
    { id: "10", nombre: "Chamicuro" },
    { id: "11", nombre: "Ese Eja" },
    { id: "12", nombre: "Harakbut" },
    { id: "13", nombre: "Ikitu" },
    { id: "14", nombre: "Iñapari" },
    { id: "15", nombre: "Iskonawa" },
    { id: "16", nombre: "Jaqaru" },
    { id: "17", nombre: "Kakataibo" },
    { id: "18", nombre: "Kakinte" },
    { id: "19", nombre: "Kandozi-Chapra" },
    { id: "20", nombre: "Kapanawa" },
    { id: "21", nombre: "Kawki" },
    { id: "22", nombre: "Kukama Kukamiria" },
    { id: "23", nombre: "Madija" },
    { id: "24", nombre: "Maijiki" },
    { id: "25", nombre: "Matsés" },
    { id: "26", nombre: "Matsigenka" },
    { id: "27", nombre: "Matsigenka Montetokunirira" },
    { id: "28", nombre: "Munichi" },
    { id: "29", nombre: "Murui-Muinani" },
    { id: "30", nombre: "Nahua" },
    { id: "31", nombre: "Nomatsigenga" },
    { id: "32", nombre: "Ocaina" },
    { id: "33", nombre: "Omagua" },
    { id: "34", nombre: "Quechua" },
    { id: "35", nombre: "Resigaro" },
    { id: "36", nombre: "Secoya" },
    { id: "37", nombre: "Sharanahua" },
    { id: "38", nombre: "Shawi" },
    { id: "39", nombre: "Shipibo-Konibo" },
    { id: "40", nombre: "Shiwilu" },
    { id: "41", nombre: "Taushiro" },
    { id: "42", nombre: "Ticuna" },
    { id: "43", nombre: "Urarina" },
    { id: "44", nombre: "Wampis" },
    { id: "45", nombre: "Yagua" },
    { id: "46", nombre: "Yaminahua" },
    { id: "47", nombre: "Yanesha" },
    { id: "48", nombre: "Yine" },
    { id: "OTRO", nombre: "Otra (Especificar)" }
];
