ALTER TABLE estudiante 
ADD COLUMN DET_ETNICA CHAR(1) NULL AFTER declaracion_etnica_pdf,
ADD COLUMN COD_ETNIA INT(11) NULL AFTER DET_ETNICA,
ADD COLUMN DET_LENGUA CHAR(1) NULL AFTER COD_ETNIA,
ADD COLUMN COD_LENGUA INT(11) NULL AFTER DET_LENGUA;
